### ISSUE TITLE
Broken links within package help files

### ISSUE THREAD

**Issue by wcornwell** [mwpennell/arbutus#16]
If you click on make_unit_tree within the arbutus help file it leads to this error message:

Error in find.package(package, lib.loc, verbose = verbose) : 
  object 'pkg' not found

**Comment by mwpennell** [comment]
@richfitz any idea what this means/how to fix it

**Comment by richfitz** [comment]
No idea - is this actually an issue or just something that happened on Will's computer? This works here for me.

**Comment by wcornwell** [comment]
This was a long time ago.  Works now.
